---
name: Test and Lint
permissions:
  contents: read
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
      - main
    paths:
      - "**.go"
jobs:
  test:
    name: lint/test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: actions/setup-go@v5
        name: Setup go environment
        with:
          go-version: "1.24"
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
          version: "~> v2"

      - name: Run tests
        run: go test -v ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          args: --verbose
      - name: Build libraries
        run: |
          ./build.sh --snapshot
