---
name: Test and Lint
permissions:
  contents: read
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
      - main
    paths:
      - '**.go'
jobs:
  test:
    name: lint/test
    runs-on: "ubuntu-latest"
    steps:

      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: actions/setup-go@v4
        name: Setup go environment
        with:
          go-version: "1.20"

      - name: Run tests
        run: go test -v ./...
      - uses: golangci/golangci-lint-action@v3
        name: Run golangci-lint
        with:
          version: "latest"
          args: --timeout=2m --verbose
