---
name: Release
permissions:
  contents: write
  packages: write
on:
  release:
    types:
      - published
jobs:

  release:
    name: release binaries
    runs-on: "ubuntu-latest"
    steps:

      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: actions/setup-go@v4
        name: Setup go environment
        with:
          go-version: "1.20"
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true

      - name: Build libraries
        run: |
          ./build.sh
      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_RELEASE_TAG: ${{ env.LATEST_RELEASE_TAG }}
        run: |
          gh release upload "$LATEST_RELEASE_TAG" \
          ./dist/kubectl-node_ssm-"$LATEST_RELEASE_TAG"-*.tar.gz
          gh release upload "$LATEST_RELEASE_TAG" \
          ./dist/kubectl-node_ssm-"$LATEST_RELEASE_TAG"-*.zip
          gh release upload "$LATEST_RELEASE_TAG" \
          ./dist/kubectl-node_ssm-"$LATEST_RELEASE_TAG"-*.sha256
